apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: teiid-operator
  namespace: teiid
spec:
  targetNamespaces:
  - teiid
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: teiid-operator
  namespace: teiid
spec:
  channel: alpha
  name: teiid
  source: community-operators
  sourceNamespace: openshift-marketplace
